config/routes.rb
Rails.application.routes.draw do

    scope module: :public do
      devise_for :users, controllers: {
        sessions: 'public/sessions'
      }
  
      root to: "homes#top"
      get '/about', to: "homes#about", as: :about
  
      resources :tips, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
        resources :post_comments, only: [:create, :destroy]
        resource :favorite, only: [:create, :destroy]
      end
  
      resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
    end
  

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions',
  }

  namespace :public do
    get 'search', to: 'searches#search'
  end

  namespace :admin do
    get 'dashboards' , to: 'dashboards#index'
    resources :users, only: [:destroy]
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :tip

  validates :user_id, presence: true
  validates :tip_id, presence: true

  validates :user_id, uniqueness: {scope: :tip_id}

  # Ensure a user can only favorite a tip once
  # validates_uniqueness_of :tip_id, scope: :user_id
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :tip

  validates :comment, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true
  validates :tip_id, presence: true
end

app/models/tip.rb
class Tip < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  validates :title, presence: true
  validates :detail, presence: true
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Tip.where(title: content)
    else
      Tip.where('title LIKE ?', '%' + content + '%')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tips, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_authentication

  private

  def configure_authentication
    if admin_controller?
      authenticate_admin!
    else
      authenticate_user! unless action_is_public? || admin_signed_in?
    end
  end
  

  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end

  def action_is_public?
    controller_name == 'homes' && action_name == 'top'
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    tip = Tip.find(params[:tip_id])
    favorite = current_user.favorites.new(tip_id: tip.id)
    favorite.save
    redirect_to tip_path(tip)
  end

  def destroy
    tip = Tip.find(params[:tip_id])
    favorite = current_user.favorites.find_by(tip_id: tip.id)
    favorite.destroy
    redirect_to tip_path(tip)
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    tip = Tip.find(params[:tip_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.tip_id = tip.id
    if comment.save
      flash[:notice] = "Comment was successfully created."
      redirect_to tip_path(tip)
    else
      flash[:alert] = "Comment could not be created."
      redirect_to tip_path(tip)
    end
  end
    
  def destroy
    PostComment.find(params[:id]).destroy
    flash[:notice] = "Comment was successfully destroyed."
    redirect_to tip_path(params[:tip_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  def new
    @tip = Tip.new
  end

  def create
    @tip = Tip.new(tip_params)
    @tip.user = current_user
    if @tip.save
      redirect_to @tip, notice: "Tip was successfully created."
    else
      render :new
    end
  end

  def index
    @tips = Tip.all
  end

  def show
    @tip = Tip.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @tip = Tip.find(params[:id])
    if @tip.user != current_user
      redirect_to tips_path, alert: "You are not authorized to edit this tips."
    end
  end

  def update
    @tip = Tip.find(params[:id])
    if @tip.update(tip_params)
      redirect_to @tip, notice: "Tip was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @tip = Tip.find(params[:id])
    @tip.destroy
    redirect_to tips_path
  end

  private

  def tip_params
    params.require(:tip).permit(:title, :detail)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tips = @user.tips
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
    @tip = Tip.find(params[:tip_id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.id == current_user.id
      @user.destroy
      redirect_to new_user_registration_path, notice: "User was successfully deleted."
    else
      redirect_to user_path(current_user), alert: "You can only delete your own account."
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :job, :career)
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AccountUs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/ff15bdfaf1.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
  <header class="shadow-sm">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to root_path, class: "navbar-brand fs-1 fw-bold d-flex align-items-center gap-3" do %>
          <span class="fs-1 fw-bold">Accountus</span>
          <i class="fa-solid fa-calculator fs-2"></i>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AccountUs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/ff15bdfaf1.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
  <header class="shadow-sm">

  <% if user_signed_in? %>
    <div class="bg-light py-2">
      <div class="container d-flex justify-content-end">
        <div class="search_form">
          <%= form_with url: public_search_path, method: :get, local: true do |f| %>
            <div class="d-flex flex-wrap align-items-center gap-2">
              <%= f.text_field :content, placeholder: "キーワード", class: "form-control form-control-sm w-auto" %>
              <%= f.select :model, options_for_select({ "user" => "User", "tip" => "Tip" }), {}, class: "form-select form-select-sm w-auto" %>
              <%= f.select :method, options_for_select({ "完全一致" => "perfect", "部分一致" => "partial" }), {}, class: "form-select form-select-sm w-auto" %>
              <%= f.submit "検索", class: "btn btn-sm btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to root_path, class: "navbar-brand fs-1 fw-bold d-flex align-items-center gap-3" do %>
          <span class="fs-1 fw-bold">AccountUs</span>
          <i class="fa-solid fa-calculator fs-2"></i>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", user_path(current_user), class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", tips_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿フォーム", new_tip_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main class="mb-auto">
    <%= yield %>
  </main>
  <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>SNS for sharing the latest news with professionals working in the accounting field.</p>
          </div>
          <div class="col-md-6">
          </div>
          <div class="col-md-2 d-flex flex-column align-items-left">
            <h6 class="text-white">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <%= link_to "/", class: "text-white-50" do %>
                  <i class="fa-solid fa-house"></i> Top
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>